import 'fake-indexeddb/auto';
import {beforeEach,expect,it} from 'vitest';
import {makeCapture} from '../lib/capture';
import {questionContext,questionImages,reconcileMaterials} from '../lib/materials';
import {saveMaterialSet,listQuestions,replaceAllQuestions,trashQuestions,saveQuestion,saveIfUnchanged,applySyncResults} from '../lib/local-db';
import {validateBackup} from '../lib/backup';
import {buildNativeRequest} from '../lib/deepseek-client';
import type {SharedMaterial} from '../lib/models';
const date='2026-09-06T00:00:00.000Z';
const material:SharedMaterial={id:'m1',title:'表格资料',text:'2025年产值为100',images:['data:image/png;base64,material'],updatedAt:date};
const children=()=>['q1','q2'].map((id,i)=>({...makeCapture('data:image/png;base64,'+id,id,date),material,stem:'第'+(i+1)+'小题',subquestionNumber:String(i+1),correctAnswer:i?'B':'A',answerConfirmed:true,inbox:false}));
beforeEach(async()=>{await replaceAllQuestions([]);});
it('一份资料生成两道独立题目与答案',async()=>{await saveMaterialSet(children());const all=await listQuestions();expect(all).toHaveLength(2);expect(new Set(all.map(q=>q.material?.id)).size).toBe(1);expect(all.map(q=>q.correctAnswer)).toEqual(['A','B']);});
it('修改一题作答不影响其他题',async()=>{await saveMaterialSet(children());const first=(await listQuestions())[0];await saveQuestion({...first,attempts:[{id:'a1',answer:'B',correct:false,answeredAt:date,mode:'practice'}]});expect((await listQuestions()).find(q=>q.id==='q2')?.attempts).toHaveLength(0);});
it('删除一个小题不删除公共资料和兄弟题',async()=>{await saveMaterialSet(children());await trashQuestions(['q1']);expect(await listQuestions()).toHaveLength(1);expect((await listQuestions())[0].material?.text).toBe(material.text);await trashQuestions(['q1'],true);expect(await listQuestions()).toHaveLength(2);});
it('修改公共资料同步到全部小题并保留作答',async()=>{await saveMaterialSet(children());const all=await listQuestions();const changed={...all[0],material:{...material,text:'更正为200',updatedAt:'2026-09-07T00:00:00.000Z'},updatedAt:'2026-09-07T00:00:00.000Z'};await saveMaterialSet([changed],[],[all[0]]);const second=(await listQuestions()).find(q=>q.id==='q2')!;expect(second.material?.text).toBe('更正为200');expect(second.analysisStale).toBe(true);});
it('编辑期间题目变化时整组提交回滚',async()=>{await saveMaterialSet(children());const before=await listQuestions();await saveQuestion({...before[0],updatedAt:'2026-09-08T00:00:00.000Z',stem:'并发编辑'});await expect(saveMaterialSet(before.map(q=>({...q,stem:'覆盖'})),[],before)).rejects.toThrow();expect((await listQuestions()).find(q=>q.id==='q2')?.stem).toBe('第2小题');});
it('共享资料更改后旧AI结果不能覆盖',async()=>{await saveMaterialSet(children());const before=await listQuestions();await saveMaterialSet([{...before[0],material:{...material,updatedAt:'2026-09-09T00:00:00.000Z',text:'新资料'}}]);expect(await saveIfUnchanged({...before[1],stem:'旧AI返回'},before[1].updatedAt)).toBe(false);});
it('选中的原资料截图仅在组保存成功后进入最近删除',async()=>{const original=makeCapture('data:image/png;base64,source','source',date);await saveQuestion(original);await saveMaterialSet(children(),[original]);expect(await listQuestions()).toHaveLength(2);expect((await listQuestions(true)).find(q=>q.id==='source')?.deletedAt).toBeTruthy();});
it('备份接受资料题组并拒绝损坏资料',()=>{expect(validateBackup({questions:children()})).toHaveLength(2);expect(()=>validateBackup({questions:[{...children()[0],material:{...material,images:'bad'}}]})).toThrow();});
it('不同同步版本的公共资料采用较新版本',async()=>{await saveMaterialSet(children());const before=await listQuestions(true);const incoming=before.map((q,i)=>i? q:{...q,material:{...material,text:'云端资料修正',updatedAt:'2026-09-10T00:00:00.000Z'}});await applySyncResults(before,incoming);expect((await listQuestions()).every(q=>q.material?.text==='云端资料修正')).toBe(true);});
it('AI得到公共资料和当前小题，图片角色按真实顺序排列',()=>{const q=children()[0];const images=questionImages(q);expect(images.map(i=>i.role)).toEqual(['shared-material','current-question']);const req=buildNativeRequest({apiKey:'test',model:'test',thinkingMode:'disabled',action:'organize',question:{...questionContext(q),stem:q.stem},imageDataUrls:images.map(i=>i.dataUrl)});expect(JSON.stringify(req)).toContain('2025年产值为100');expect(JSON.stringify(req)).not.toContain('第2小题');});
it('无资料的旧题原样兼容',()=>{const q=makeCapture('','old',date);expect(reconcileMaterials([q])[0]).toEqual(q);expect(questionContext(q).sharedMaterial).toBeUndefined();});
